version: '3.8'
services:
  financial-bot:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
      - ./.env:/app/.env
      - ./user_data:/app/user_data
    environment:
      - PYTHONUNBUFFERED=1
