version: "3.8"
services:
  financial-bot:
    build: .
    container_name: financial-bot
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      # Set these as needed:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
      - MARKETAUX_API_KEY=${MARKETAUX_API_KEY}
      - USE_GOOGLE_EMBEDDINGS=0
      - LOCAL_EMBED_MODEL=all-MiniLM-L6-v2
      - HF_EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PORT=5001
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
      - ./.env:/app/.env:ro
      - ./user_data:/app/user_data
      - ./templates:/app/templates
      - ./static:/app/static
      # cache for huggingface / sentence-transformers / torch models
      - hf_cache:/root/.cache/huggingface
      - torch_cache:/root/.cache/torch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hf_cache:
  torch_cache:
